services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
      - ../docker/credentials:/app/credentials:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
      - ENVIRONMENT=development
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - bot_network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    # command: start --config /etc/ngrok.yml --all
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge 